### PR TITLE
Add proposals directory for storing proposal & Add TEMPLATE.md to guide how to write a proposal

### PR DESCRIPTION
**Pull request by yuzp1996**
Maybe we should add a proposal template for those who want to contribute? So when people want to make some contribution, they can describe their implementation in the proposal

Signed-off-by: yuzhipeng <yuzp1996@qq.com>

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
This is great. But I guess we can put a link to this template somewhere, so people can easily know it.

**Comment by yuzp1996** [comment]
> This is great. But I guess we can put a link to this template somewhere, so people can easily know it.

Hi! I don't think README.md is a good place to put links. Maybe we need a file like CONTRIBUTING.md so that we can put the link in it.

**Comment by LinuxSuRen** [comment]
> Maybe we need a file like CONTRIBUTING.md so that we can put the link in it.

+1 from me

**Review by LinuxSuRen — APPROVED** [review]

**Comment by yuzp1996** [comment]
Hi @LinuxSuRen  I am sorry to bother you.  Can you help me merge this pullrequest or what should I should do to merge this pullrequest ?   I don't have permission to merge this PR now

**Pull request merged**
